package com.vaadin.flow.starter.app.backend;

import java.io.Serializable;

public class Category implements Serializable {

    private Long categoryId = null;

    private String categoryName = "";

    public Category() {
    }

    public Category(String categoryName) {
        this.categoryName = categoryName;
    }

    public Category(Category other) {
        if (other != null) {
            this.categoryName = other.getCategoryName();
            this.categoryId = other.getCategoryId();
        } else {
            this.categoryName = "(undefined)";
        }
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Get the value of categoryName
     *
     * @return the value of categoryName
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Set the value categoryName
     *
     * @param categoryName
     *            new value of categoryName
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Category{" + getCategoryId() + ":" + getCategoryName() + '}';
    }
}
