package com.vaadin.flow.demo.freestarter.backend;

import java.io.Serializable;

public class Category implements Serializable {

    /** A null object, to avoid NullPointerExceptions. */
    public static final Category UNDEFINED = new Category("(undefined)");

    private Long id = null;

    private String name = "";

    public Category() {
    }

    public Category(String name) {
        this.name = name;
    }

    public Category(Category other) {
        if (other == null) {
            other = UNDEFINED;
        }
        this.name = other.getName();
        this.id = other.getId();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get the value of name
     *
     * @return the value of name
     */
    public String getName() {
        return name;
    }

    /**
     * Set the value name
     *
     * @param name
     *            new value of name
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Category{" + getId() + ":" + getName() + '}';
    }
}
