package com.vaadin.flow.demo.freestarter.backend;

import java.io.Serializable;
import java.time.LocalDate;

public class Review implements Serializable {

    private Long id = null;
    private int score;
    private String name = "";
    private LocalDate date;
    private Category category;
    private int count;

    public Review() {
        reset();
    }

    public Review(int score, String name, LocalDate date,
                  Category category, int count) {
        this.score = score;
        this.name = name;
        this.date = date;
        this.category = new Category(category);
        this.count = count;
    }

    public Review(Review other) {
        this(other.getScore(), other.getName(), other.getDate(), other.getCategory(),
                other.getCount());
        this.id = other.getId();
    }

    /**
     * Resets all fields to their default values.
     */
    public void reset() {
        this.id = null;
        this.score = 1;
        this.name = "";
        this.date = LocalDate.now();
        this.category = Category.UNDEFINED;
        this.count = 1;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get the value of score
     *
     * @return the value of score
     */
    public int getScore() {
        return score;
    }

    /**
     * Set the value of score
     *
     * @param score
     *            new value of Score
     */
    public void setScore(int score) {
        this.score = score;
    }

    /**
     * Get the value of name
     *
     * @return the value of name
     */
    public String getName() {
        return name;
    }

    /**
     * Set the value of name
     *
     * @param name
     *            new value of name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the value of category
     *
     * @return the value of category
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Set the value of category
     *
     * @param category
     *            new value of category
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * Get the value of date
     *
     * @return the value of date
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Set the value of date
     *
     * @param date
     *            new value of date
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Get the value of count
     *
     * @return the value of count
     */
    public int getCount() {
        return count;
    }

    /**
     * Set the value of count
     *
     * @param count
     *            new value of count
     */
    public void setCount(int count) {
        this.count = count;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Review{" + "id=" + getId() + ", score=" + getScore() + ", name=" + getName()
                + ", category=" + getCategory() + ", date=" + getDate()
                + ", count=" + getCount() + '}';
    }

}
